modLoader = "javafml"
loaderVersion = "[49,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/growthcraft/trapper/issues"

[[mods]]
id = "growthcrafttrapper"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = ["${mod_authors}"]
updateJSONURL = ""
screenshots = []
logoFile = ""

[[dependencies.growthcrafttrapper]]
modId = "neoforge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.growthcrafttrapper]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
