modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/growthcraft/trapper/issues"

[[mods]]
modId = "growthcraft_trapper"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = ["${mod_authors}"]
updateJSONURL = ""
screenshots = []
logoFile = ""

[[dependencies.growthcraft_trapper]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.growthcraft_trapper]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
